import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: "nosana | Chat",
  description: "Generated by create next app",
  icons: {
    icon: "/nosana.png",
    apple: "/nosana.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.className} ${spaceGrotesk.variable} min-h-screen antialiased flex`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
